# Starship configuration
# https://starship.rs/config

format = """\
$username\
$hostname\
$conda\
$python\
$env_var\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$custom\
$line_break\
$shlvl\
$jobs\
$sudo\
$status\
$cmd_duration\
$character\
"""
add_newline = true
command_timeout = 750

[character]
format = "[â¯](bold) "

[cmd_duration]
format = "[$duration]($style) "
min_time = 10_000

[conda]
# Conda likes to change the prompt, use this to stop it so starship wins:
#   conda config --set changeps1 False
format = "[$symbol$environment]($style) "

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 2
read_only = "ğŸ›‡"
read_only_style = "red bold"

[env_var._OPVARS_PROMPT]
default = ''
format = '[$env_value]($style)'
style = "red bold"

[git_branch]
format = '\($branch\) '

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted]($deleted_style))'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
modified = ''
ahead = "â–²${count}"
diverged = "â–²${ahead_count}â–¼${behind_count}"
behind = "â–¼${count}"
deleted = "Ã—"

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false
ssh_symbol = "ğ•Š "
style = "bold green"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "ğ•"

[python]
format = '[(\($virtualenv\) )]($style)'

[shlvl]
disabled = false

[status]
disabled = false
format = '[*$status]($style) '

[sudo]
disabled = false
format = "[$symbol]($style) "
symbol = "Â§"
style = "red bold"

[username]
format = "[$user]($style) "
